---
apiVersion: v1
kind: Service
metadata:
  name: getting-started
  labels:
    app: getting-started
spec:
  type: ClusterIP
  selector:
    app: getting-started
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
